title = "NYC Mesh"
baseURL = "https://www.nycmesh.net/"
languageCode = "en-us"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
summaryLength = 10

[params]
  title = "NYC Mesh"
  description = "Join our community-owned network to replace your current internet connection."
  images = ["/img/3d.png"]

[markup]
	[markup.blackFriday]
		hrefTargetBlank = true
	[markup.tableOfContents]
		endLevel = 3
		ordered = false
		startLevel = 2
