title = "NYC Mesh"
baseURL = "https://www.nycmesh.net/"
languageCode = "en-us"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
summaryLength = 10

[params]
  title = "NYC Mesh"
  description = "Join our community-owned network to replace your current internet connection."
  images = ["/img/splash9.jpg"]